# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Realtek network device drivers.
#

obj-$(CONFIG_8139CP) += 8139cp.o
obj-$(CONFIG_8139TOO) += 8139too.o
obj-$(CONFIG_ATP) += atp.o
r8169-objs += r8169_main.o r8169_firmware.o
obj-$(CONFIG_R8169) += r8169.o
obj-$(CONFIG_R8101_OEM) += r8101/
obj-$(CONFIG_R8125_OEM) += r8125/
obj-$(CONFIG_R8168_OEM) += r8168/
obj-$(CONFIG_R8169_OEM) += r8169/
